source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'activerecord-tableless'
gem 'figaro'
gem 'foundation-rails'
gem 'gibbon'
gem 'google_drive'
gem 'haml-rails'
gem 'high_voltage'
gem 'puma'
gem 'simple_form'
gem 'therubyracer', :platform=>:ruby  
gem 'mysql2'
gem 'protected_attributes'
gem 'jquery-ui-rails'
gem 'wice_grid'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_19, :mri_20, :rbx]
  gem 'html2haml'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'sqlite3'
end
group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'thin'
end
